services:
  mysql_206:
    env_file:
      - .env
    container_name: mysql_206
    image: mysql:8.0.33  # Versão estável recomendada
    restart: unless-stopped
    command:
      - --default-authentication-plugin=mysql_native_password  # Formato correto
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - ./mysql_206:/var/lib/mysql
    ports:
      - 3306:3306